### ISSUE TITLE
Keep blocking query data

### ISSUE THREAD

**Issue by jamesshieh** [mike-weinberg/dreddshift#5]
Can we keep the blocking query xid/pid as separate columns in the final result along with the blocked xid pid? if already available easily its probably worth keeping the userids/usernames from the blocked/blocking as well. That will also give us more flexibility to join in more data thats needed from other tables so this query needs to change less.

**Comment by mike-weinberg** [comment]
yup we should do this. resolution would be a PR adding those values after https://github.com/mike-weinberg/dreddshift/blob/master/views/admin/blocked_locks.sql#L163 
https://github.com/mike-weinberg/dreddshift/blob/master/views/admin/blocked_locks.sql#L163

**Comment by jamesshieh** [comment]
@mike-weinberg are you taking or do you want me to PR?
